In [1]:
#Exp.No.:6

In [2]:
#Aim:To perform operation of Sampling and Population

In [3]:
#Name:Snehal Sunilrao Wakde
#Roll No.:63
#Sec.:C
#Subject:DSS

In [4]:
#importing the basic library
import pandas as pd

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\PC'

In [7]:
os.chdir('C:\\Users\\PC\\OneDrive\\Desktop')

In [8]:
data=pd.read_csv("heart.csv")

In [9]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [10]:
data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [11]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [12]:
list(data.columns)

['age',
 'sex',
 'cp',
 'trestbps',
 'chol',
 'fbs',
 'restecg',
 'thalach',
 'exang',
 'oldpeak',
 'slope',
 'ca',
 'thal',
 'target']

In [13]:
age_above_60=data[data["age"]>60]
print(age_above_60)

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
2      70    1   0       145   174    0        1      125      1      2.6
3      61    1   0       148   203    0        1      161      0      0.0
4      62    0   0       138   294    1        1      106      0      1.9
10     71    0   0       112   149    0        1      125      0      1.6
21     67    0   0       106   223    0        1      142      0      0.3
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
989    71    0   1       160   302    0        1      162      0      0.4
999    67    1   0       125   254    1        1      163      0      0.2
1000   64    1   0       145   212    0        0      132      0      2.0
1002   66    1   0       112   212    0        0      132      1      0.1
1016   65    1   3       138   282    1        0      174      0      1.4

      slope  ca  thal  target
2         0   0     3       0
3         2   1     3       0
4         1   3     2       0
10        1   0     2       1
21        2   2     2       1
...     ...  ..   ...     ...
989       2   2     2       1
999       1   2     3       0
1000      1   2     1       0
1002      2   1     2       0
1016      1   1     2       0

[272 rows x 14 columns]

In [14]:
data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [15]:
print(len(age_above_60))

272

In [16]:
chol_above_250=data[data["chol"]>250]
print(chol_above_250)

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
4      62    0   0       138   294    1        1      106      0      1.9
6      58    1   0       114   318    0        2      140      0      4.4
7      55    1   0       160   289    0        0      145      1      0.8
9      54    1   0       122   286    0        0      116      1      3.2
11     43    0   0       132   341    1        0      136      1      3.0
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
1016   65    1   3       138   282    1        0      174      0      1.4
1017   53    1   0       123   282    0        1       95      1      2.0
1021   60    1   0       125   258    0        0      141      1      2.8
1022   47    1   0       110   275    0        0      118      1      1.0
1023   50    0   0       110   254    0        0      159      0      0.0

      slope  ca  thal  target
4         1   3     2       0
6         0   3     1       0
7         1   1     3       0
9         1   2     2       0
11        1   0     3       0
...     ...  ..   ...     ...
1016      1   1     2       0
1017      1   2     3       0
1021      1   1     3       0
1022      1   1     2       0
1023      2   0     2       1

[424 rows x 14 columns]

In [17]:
data.shape

(1025, 14)

In [18]:
data.size

14350

In [19]:
data.ndim

2

In [20]:
data.isna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1021,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1022,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1023,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1024,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [21]:
data.isna().any()

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
target      False
dtype: bool

In [22]:
data.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64